eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: students
            uri: http://localhost:8090
            predicates:
              - Path=/api/v1/students/**
            filters:
              - AddResponseHeader=X-Powered_by,Migeri Gateway Service
          - id: schools
            uri: http://localhost:8070
            predicates:
              - Path=/api/v1/schools/**
      discovery:
        locator:
          enabled: true
management:
  tracing:
    sampling:
      probability: 1.0
